language: objective-c 

# macOS and Xcode Version
os: osx
osx_image: xcode11.5

# Build dependencies
# Travis has trouble with python3, which SPIRV-Tools requires,
# so skip the SPIRV-Tools build, and use templeted headers instead.
install:
  - ./fetchDependencies -v --skip-spirv-tools-build

script:
  - xcodebuild -project MoltenVKPackaging.xcodeproj -scheme "MoltenVK Package"
  - xcodebuild -workspace Demos/Demos.xcworkspace -scheme "Cube-macOS"

